# Generated by Django 2.1.5 on 2020-03-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='shared_pics')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('tag_one', models.CharField(blank=True, max_length=50)),
                ('tag_two', models.CharField(blank=True, max_length=50)),
                ('slug', models.ImageField(unique=True, upload_to='')),
            ],
        ),
    ]
