# Generated by Django 2.1.5 on 2020-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='era',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
