# Generated by Django 2.1.5 on 2020-03-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0003_pictures_era'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='slug',
        ),
    ]
