# Generated by Django 2.1.5 on 2020-03-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0004_remove_pictures_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='when_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
