# Generated by Django 2.1.5 on 2020-03-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0005_pictures_when_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='shared_pics')),
                ('title', models.CharField(blank=True, max_length=190)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('tag_one', models.CharField(blank=True, max_length=50)),
                ('tag_two', models.CharField(blank=True, max_length=50)),
                ('era', models.CharField(blank=True, max_length=20)),
                ('when_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pictures',
                'ordering': ['when_added'],
            },
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nowandthen.Picture'),
        ),
    ]
