# Generated by Django 2.1.5 on 2020-03-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0006_auto_20200313_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='image',
        ),
    ]
